name       : mate-system-monitor
version    : 1.24.0
release    : 14
source     :
    - https://github.com/mate-desktop/mate-system-monitor/archive/v1.24.0.tar.gz : 75059f39fca9f9c3243eb945a1dfb6aab312d74bb830dbb21e296e3dd04fc725
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE System Monitor
description: |
    MATE System Monitor
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-maintainer-mode \
        --disable-static \
        --enable-systemd
build      : |
    %make
install    : |
    %make_install
