name       : mate-system-monitor
version    : 1.26.0
release    : 20
source     :
    - https://github.com/mate-desktop/mate-system-monitor/releases/download/v1.26.0/mate-system-monitor-1.26.0.tar.xz : 83472c3add79e52b2fb3c1bc55f33f968c71a2b90e2b62027ad688c1cecc338f
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE System Monitor
description: |
    MATE System Monitor
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
setup      : |
    %configure --disable-maintainer-mode \
        --disable-static \
        --enable-systemd
build      : |
    %make
install    : |
    %make_install
