name       : mate-system-monitor
version    : 1.18.1
release    : 5
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-system-monitor-1.18.1.tar.xz : 7a2aa5c6364d5deb9e9c3ff0ece65f9485a6039c47d81c0681ae1702523b1ff6
license    : GPL-2.0
component  : desktop.mate
summary    : MATE System Monitor
description: |
    MATE System Monitor
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsystemd)
    - pkgconfig(libwnck-3.0)
    - itstool
setup      : |
    %configure --enable-systemd
build      : |
    %make
install    : |
    %make_install
