name       : mate-system-monitor
version    : 1.22.0
release    : 11
source     :
    - https://github.com/mate-desktop//mate-system-monitor/archive/v1.22.0.tar.gz : 94477224c93aaf0689220857d43d9e49da74e5bef9ae93ec6ca318c12710d2cb
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE System Monitor
description: |
    MATE System Monitor
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-maintainer-mode \
        --disable-static \
        --enable-systemd
build      : |
    %make
install    : |
    %make_install
