name       : mate-system-monitor
version    : 1.24.1
release    : 16
source     :
    - https://github.com/mate-desktop/mate-system-monitor/releases/download/v1.24.1/mate-system-monitor-1.24.1.tar.xz : 1fa384fae8be0384dbfa7bb32acdbda977745185e59570bd3869ea6e382559c4
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE System Monitor
description: |
    MATE System Monitor
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
setup      : |
    %configure --disable-maintainer-mode \
        --disable-static \
        --enable-systemd
build      : |
    %make
install    : |
    %make_install
